### ISSUE TITLE
The bot does not respond to any message

### ISSUE THREAD

**Issue by Mairoooon** [Sank6/Backup#6]
I configured the dashboard and it worked correctly but when executing commands on a server I don't receive any response from the bot, why is this?

**Comment by Sank6** [comment]
Are you using the right prefix? Try just pinging the bot and it should say respond with its prefix.

**Comment by Mairoooon** [comment]
@Sank6 I added the prefix in .env and the one i added was `+` but it doesn't respond

**Comment by Sank6** [comment]
Does the bot have perms to send messages?

**Comment by Mairoooon** [comment]
It responds with a mention, but it doesn't respond to the default prefix, and for it to work with a prefix I must use @bot prefix + and then if it works with the custom prefix

**Comment by Sank6** [comment]
Fixed: 06f4740.
